site_name: Estatística Aplicada
site_url: https://igorbarcosta.github.io/estatistica/
theme:
  name: material
  language: pt-BR
  features:
    - navigation.path
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow
    - search.highlight
    - search.share
    - content.code.annotate
    - content.code.copy
    - content.code.select
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: Inter
    code: JetBrains Mono
  icon:
    logo: material/chart-box-outline


markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed  
  - toc:
      permalink: true

repo_url: https://github.com/igorbarcosta/estatistica
repo_name: igorbarcosta/estatistica
nav:
  - Início: index.md
  - Roteiros de Aula: 
      - roteiros/index.md
      - Aula 01: roteiros/aula_01.md
      - Aula 02: roteiros/aula_02.md
  - Fundamentação Teórica: 
    - material/index.md
    - Fundamentos:
      - Visão Geral: 
        - Definição de Estatística: material/fundamentos/visao_geral/definicao_de_estatistica.md
        - Conjunto de Dados: material/fundamentos/visao_geral/conjunto_de_dados.md
        - Ramos da Estatística: material/fundamentos/visao_geral/ramos_da_estatistica.md
      - Classificação dos Dados:
        - Tipos de Dados: material/fundamentos/classificacao_dos_dados/tipos_de_dados.md
        - Níves de Mensuração: material/fundamentos/classificacao_dos_dados/niveis_de_mensuracao.md
      - Investigação Estatística: 
        - O Ciclo PPDAC: material/fundamentos/investigacao_estatistica/o_ciclo_ppdac.md
        - Técnicas de Amostragem: material/fundamentos/investigacao_estatistica/tecnicas_de_amostragem.md
        - Vieses de Amostragem: material/fundamentos/investigacao_estatistica/vieses_de_amostragem.md
    - Estatística Descritiva:
      - Distribuições de Frequência:
        - Tabelas de Frequência: material/estatistica_descritiva/distribuicoes_de_frequencia/tabelas_de_frequencia.md
        - Representações Gráficas: material/estatistica_descritiva/distribuicoes_de_frequencia/representacoes_graficas.md
        - Erros comuns e Armadilhas: material/estatistica_descritiva/distribuicoes_de_frequencia/erros_comuns_e_armadilhas.md
      - Medidas de Tendência Central:
        - Média, Mediana e Moda: material/estatistica_descritiva/medidas_de_tendencia_central/media_mediana_e_moda.md
        - Média Ponderada e Média de Dados Agrupados: material/estatistica_descritiva/medidas_de_tendencia_central/media_ponderada.md
        - As Formas das Distribuições: material/estatistica_descritiva/medidas_de_tendencia_central/as_formas_das_distribuicao.md
      - Medidas de Variação:
        - Amplitude: material/estatistica_descritiva/medidas_de_variacao/amplitude.md
        - Variância e Desvio Padrão: material/estatistica_descritiva/medidas_de_variacao/variancia_e_desvio_padrao.md
        - Interpretando o Desvio Padrão: material/estatistica_descritiva/medidas_de_variacao/interpretando_o_desvio_padrao.md
        - Devio Padrão dos Dados Agrupados: material/estatistica_descritiva/medidas_de_variacao/desvio_padrao_dos_dados_agrupados.md
        - Coeficiente de Variação: material/estatistica_descritiva/medidas_de_variacao/coeficiente_de_variacao.md
      - Medidas de Posição: 
        - Quartis: material/estatistica_descritiva/medidas_de_posicao/quartis.md
        - Percentis e Outras Separatrizes: material/estatistica_descritiva/medidas_de_posicao/percentis_e_outras_separatrizes.md
        - O Escore Padrão:  material/estatistica_descritiva/medidas_de_posicao/o_escore_padrao.md
    - Probabilidade:
      - material/probabilidade/index.md
    - Estatística Inferencial:
      - material/estatistica_inferencial/index.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/igorbarcosta
    - icon: fontawesome/solid/envelope
      link: mailto:igor.costa@ifpb.edu.br
  generator: false
copyright: "© 2025 Igor Barbosa da Costa. Todos os direitos reservados."

extra_javascript:
  #Apesar de colocar aqui, o arquivo precisa ser colocado no final de cada .md que fizer uso
  - https://cdn.jsdelivr.net/npm/chart.js

extra_css:
  - assets/stylesheets/extra.css