site_name: Estatística Aplicada
site_url: https://igorbarcosta.github.io/estatistica/
theme:
  name: material
  language: pt-BR
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - search.highlight
    - search.share
    - content.code.annotate
    - content.code.copy
    -
  palette:
    scheme: default
    primary: green
    accent: red
  font:
    text: Roboto
    code: Roboto Mono
  favicon: images/favicon.ico
  logo: images/logo_ifpb.png
  colors:
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

repo_url: https://github.com/igorbarcosta/estatistica
repo_name: igorbarcosta/estatistica
nav:
  - Início: index.md
  - Roteiros de Aula:
      - Aula 1: roteiros/aula1.md
      - Aula 2: roteiros/aula2.md
  - Conteúdos Estatísticos:
      - Estatística Descritiva: conteudos/descritiva.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/igorbarcosta
    - icon: fontawesome/solid/envelope
      link: mailto:igor.costa@ifpb.edu.br
  generator: false
copyright: "© 2025 Igor Barbosa da Costa. Todos os direitos reservados."

