name: Deploy MkDocs

on:
  push:
    branches:
      - main  # ou 'master', se for o seu caso

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install mkdocs-material

      - name: Deploy no GitHub Pages
        run: mkdocs gh-deploy --force
